name: Build and Deploy
on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.*'
  pull_request:
    branches:
      - master
env:
  MAVEN_OPTS: "-Xmx4G -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Compile & Bootstrap
        run: mvn -B compile

      - name: Run Tests
        run: mvn -B -Drascal.test.memory=4 test

      - name: Publish Test Report on github action
        if: ${{ always() && github.event_name != 'pull_request' }} # to bad this doesn't work nicely with external pull requests
        uses: scacap/action-surefire-report@v1
        with:
          check_name: "Test Report"

      - name: Attach artifact
        id: build-artifact
        uses: SWAT-engineering/maven-full-artifacts-action@v1

